import type { Lesson } from '../../types'

// Lesson 1 — Sequencing & Cargo.
// Starts with tight shortest-path mazes, then layers in pickup/drop cargo runs.
export const lesson1: Lesson = {
  id: 'lesson-1-sequencing-cargo',
  version: 4,
  title: 'Sequencing & Cargo',
  subtitle: 'Plan the exact route — then start hauling cargo.',
  sequence: 1,
  skillIds: ['sequencing', 'planning'],
  steps: [
    {
      id: 'l1-intro',
      type: 'concept',
      title: 'Plan every move',
      body: 'A program is a list of moves the explorer follows in order, top to bottom.\n\nThe maps here are mazes with rocks. There is usually **one tight route** — plan the whole path in your head before you press Run.',
    },
    {
      id: 'l1-q1',
      type: 'sequence',
      goal: 'Thread the maze',
      prompt: 'Rocks block the easy way. Find the shortest route to the treasure — no wasted moves.',
      map: {
        rows: 4,
        cols: 4,
        start: { row: 3, col: 0 },
        goal: { row: 0, col: 3 },
        obstacles: [
          { row: 3, col: 1 },
          { row: 0, col: 2 },
          { row: 2, col: 2 },
        ],
      },
      availableCommands: ['up', 'right', 'down', 'left'],
      successRule: 'shortestPath',
      optimal: 6,
      solution: ['up', 'up', 'right', 'right', 'right', 'up'],
      feedback: {
        correct: 'Tight and clean — six moves, not one wasted.',
        hints: [
          'You cannot go right first — a rock is in the way.',
          'Climb a couple of rows, then cross, then finish climbing.',
        ],
      },
    },
    {
      id: 'l1-q2',
      type: 'sequence',
      goal: 'Grab the key, unlock the door',
      prompt: 'A locked door blocks the only gap in the wall. Climb up to grab the key first, then come back and walk through.',
      map: {
        rows: 4,
        cols: 4,
        start: { row: 3, col: 0 },
        goal: { row: 0, col: 3 },
        obstacles: [
          { row: 1, col: 0 },
          { row: 1, col: 1 },
          { row: 1, col: 3 },
        ],
        keys: [{ row: 2, col: 1 }],
        doors: [{ row: 1, col: 2 }],
      },
      availableCommands: ['up', 'right', 'down', 'left'],
      successRule: 'reachGoal',
      solution: ['right', 'up', 'right', 'up', 'up', 'right'],
      feedback: {
        correct: 'Key first, then the door — you planned the detour perfectly.',
        hints: [
          'The wall only has one gap, and it is a locked door — you need the key before you reach it.',
          'Step onto the key tile to pick it up, then climb up through the door.',
        ],
      },
    },
    {
      id: 'l1-cargo',
      type: 'concept',
      title: 'Pick up & drop off',
      body: 'Now you carry cargo. Drive onto a **gem**, then play **Pick up** to grab it.\n\nCarry it to its matching **flag** and play **Drop**. You can only hold one item at a time, and you must finish one job before the next.\n\nWatch for **teleport swirls** (step on one and you appear on its twin) and **slippery ice** that keeps sliding you until a wall stops you!',
    },
    {
      id: 'l1-q3',
      type: 'sequence',
      goal: 'Teleport the cargo',
      prompt: 'Grab the gem, then ride the teleport swirl up to the top row before dropping it at the flag.',
      map: {
        rows: 3,
        cols: 5,
        start: { row: 2, col: 0 },
        goal: { row: 0, col: 0 },
        obstacles: [{ row: 1, col: 2 }],
        tasks: [{ from: { row: 2, col: 2 }, to: { row: 0, col: 2 }, label: 'the gem' }],
        teleports: [{ a: { row: 2, col: 3 }, b: { row: 0, col: 3 } }],
      },
      availableCommands: ['right', 'up', 'down', 'left'],
      availableActions: ['pickup', 'drop'],
      successRule: 'reachGoal',
      solution: ['right', 'right', 'pickup', 'right', 'left', 'drop', 'left', 'left'],
      feedback: {
        correct: 'You let the teleport carry the cargo across — clever routing.',
        hints: [
          'A rock sits above the gem, so you cannot climb straight up.',
          'Step onto the swirl on the bottom row — it lifts you to the top row.',
        ],
      },
    },
    {
      id: 'l1-q4',
      type: 'sequence',
      goal: 'Four-slide chain',
      prompt: 'Each move sends you sliding until a rock or the edge catches you. Think about where each slide ENDS before you press Run — the landing spot of one slide is the launch pad for the next.',
      map: {
        rows: 5,
        cols: 5,
        start: { row: 4, col: 0 },
        goal: { row: 0, col: 4 },
        obstacles: [
          { row: 4, col: 3 },
          { row: 1, col: 2 },
        ],
        ice: [
          { row: 4, col: 1 },
          { row: 4, col: 2 },
          { row: 3, col: 2 },
          { row: 2, col: 2 },
          { row: 2, col: 3 },
          { row: 2, col: 4 },
          { row: 1, col: 4 },
        ],
      },
      availableCommands: ['right', 'up', 'down', 'left'],
      successRule: 'reachGoal',
      solution: ['right', 'up', 'right', 'up'],
      feedback: {
        correct: 'Four slides chained — each rock and wall was a stepping stone to the next.',
        hints: [
          'Each move slides you until a wall or the edge stops you, so plan by where each slide ends — not how far it goes.',
          'Work one slide at a time: see where a slide drops you, and use that landing spot as the launch pad for the next.',
        ],
      },
    },
    {
      id: 'l1-q5',
      type: 'sequence',
      goal: 'The full haul',
      prompt: 'Carry job 1 up the left, then job 2 down the right, weaving past the center rocks.',
      map: {
        rows: 4,
        cols: 5,
        start: { row: 3, col: 0 },
        goal: { row: 3, col: 4 },
        obstacles: [
          { row: 2, col: 2 },
          { row: 1, col: 2 },
        ],
        tasks: [
          { from: { row: 3, col: 1 }, to: { row: 0, col: 1 }, label: 'job 1' },
          { from: { row: 0, col: 3 }, to: { row: 3, col: 3 }, label: 'job 2' },
        ],
      },
      availableCommands: ['right', 'up', 'down', 'left'],
      availableActions: ['pickup', 'drop'],
      successRule: 'reachGoal',
      solution: [
        'right',
        'pickup',
        'up',
        'up',
        'up',
        'drop',
        'right',
        'right',
        'pickup',
        'down',
        'down',
        'down',
        'drop',
        'right',
      ],
      feedback: {
        correct: 'A long double haul, delivered cleanly — you have mastered sequencing.',
        hints: [
          'Job 1 climbs the far-left column; the rocks never block it.',
          'Job 2 rides down the column to the right of the rocks.',
        ],
      },
    },
  ],
}
